
package Insert_Dialogs;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import Main.Base_Datos;

/**
 *
 * @author luism
 */
public class CustomerPreferencesInsertDialog extends javax.swing.JDialog {

    /**
     * Creates new form CustomerPreferencesInsertDialog
     */
    private final Base_Datos BD;
    private final HashMap ht_carFeatures;
    private final HashMap ht_Customers;
    
    public CustomerPreferencesInsertDialog(java.awt.Frame parent, Base_Datos BD) {
        super(parent, true);
        initComponents();
        this.BD = BD;
        ht_carFeatures = new HashMap<String, Integer>();
        buildCombo_CarFeature(BD);
        
        ht_Customers = new HashMap<String,Integer>();
        buildCombo_Customer(BD);
        
    }
    
    private void buildCombo_Customer(Base_Datos BD){
        final String sql = "select \"customer_ID\" "
                + "FROM public.\"Customers\"";
        try{
            ResultSet rs = BD.query(sql);
            while(rs.next()){
                int id = rs.getInt(1);
                String label =rs.getString(1);
                customer_IDCombobox.addItem(label);
                ht_Customers.put(label, id);
            }
        }catch(SQLException ex){
            
        }
    }
    
    private void buildCombo_CarFeature(Base_Datos BD){
        final String sql = "select \"car_Feature_ID\", "
                + "\"car_Feature_Description\" "
                + "FROM public.\"Car_Features\"";
        try{
            ResultSet rs = BD.query(sql);
            while (rs.next()){
                int id = rs.getInt(1);
                String label = rs.getString(2);
                car_Feature_IDCombobox.addItem(label);
                ht_carFeatures.put(label, id);
            }
        }catch(SQLException ex){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        car_Feature_IDCombobox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        customer_IDCombobox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        details_txt = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Insert New Customer Preference");

        car_Feature_IDCombobox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                car_Feature_IDComboboxFocusLost(evt);
            }
        });
        car_Feature_IDCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                car_Feature_IDComboboxActionPerformed(evt);
            }
        });

        jLabel1.setText("Car Feature ID:");

        customer_IDCombobox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                customer_IDComboboxFocusLost(evt);
            }
        });
        customer_IDCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_IDComboboxActionPerformed(evt);
            }
        });

        jLabel3.setText("Customer ID:");

        jLabel4.setText("Details:");

        details_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                details_txtActionPerformed(evt);
            }
        });

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customer_IDCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(car_Feature_IDCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(details_txt))
                .addGap(77, 77, 77))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancelButton)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(car_Feature_IDCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customer_IDCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(details_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton)
                    .addComponent(CancelButton))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        String ID ="DEFAULT";
        Integer car_Feature_ID = (Integer) ht_carFeatures.get(car_Feature_IDCombobox.getSelectedItem());
        Integer customer_ID = (Integer) ht_Customers.get(customer_IDCombobox.getSelectedItem());
        String details = details_txt.getText();
        
        StringBuilder sql 
                = new StringBuilder("INSERT INTO public.\"Customer_Preferences\""
                        + "(\"customer_Preference_ID\", \"car_Feature_ID\", \"customer_ID\", "
                        + "\"customer_Preference_Details\") VALUES (");
        sql.append(ID);
        sql.append(",");
        sql.append(car_Feature_ID.intValue());
        sql.append(",");
        sql.append(customer_ID.intValue());
        sql.append(",");
        sql.append("'"+details+"'");
        sql.append(")");
        System.out.println(sql.toString());
        try {
            BD.update( sql.toString() );
            JOptionPane.showMessageDialog(this, "New preference has been added!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error adding new preference: \n" + ex.toString());
            System.out.println( ex.getMessage() );
        }
        setVisible(false);
    }//GEN-LAST:event_AddButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void car_Feature_IDComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_car_Feature_IDComboboxActionPerformed
        
    }//GEN-LAST:event_car_Feature_IDComboboxActionPerformed

    private void customer_IDComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_IDComboboxActionPerformed
        
    }//GEN-LAST:event_customer_IDComboboxActionPerformed

    private void details_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_details_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_details_txtActionPerformed

    private void car_Feature_IDComboboxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_car_Feature_IDComboboxFocusLost
        String text = car_Feature_IDCombobox.getSelectedItem().toString();
        if (text.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Missing Car Feature ID");
        }
    }//GEN-LAST:event_car_Feature_IDComboboxFocusLost

    private void customer_IDComboboxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customer_IDComboboxFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_IDComboboxFocusLost

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JComboBox<String> car_Feature_IDCombobox;
    private javax.swing.JComboBox<String> customer_IDCombobox;
    private javax.swing.JTextField details_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
