
package Insert_Dialogs;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import Main.Base_Datos;

/**
 *
 * @author luism
 */
public class FeaturesonCarsforSaleInsertDialog extends javax.swing.JDialog {

    /**
     * Creates new form FeaturesonCarsforSaleInsertDialog
     */
    
    private final Base_Datos BD;
    private final HashMap ht_carforsaleID;
    private final HashMap ht_carFeatures;
    
    public FeaturesonCarsforSaleInsertDialog(java.awt.Frame parent, Base_Datos BD) {
        super(parent, true);
        initComponents();
        this.BD = BD;
        ht_carFeatures = new HashMap<String, Integer>();
        buildCombo_CarFeature(BD);
        ht_carforsaleID = new HashMap<String,Integer>();
        buildCombo_carforsaleID(BD);
    }
    
    private void buildCombo_CarFeature(Base_Datos BD){
        final String sql = "select \"car_Feature_ID\", "
                + "\"car_Feature_Description\" "
                + "FROM public.\"Car_Features\"";
        try{
            ResultSet rs = BD.query(sql);
            while (rs.next()){
                int id = rs.getInt(1);
                String label = rs.getString(2);
                car_Feature_IDCombobox.addItem(label);
                ht_carFeatures.put(label, id);
            }
        }catch(SQLException ex){
            
        }
    }
    private void buildCombo_carforsaleID(Base_Datos BD){
            final String sql = "select \"car_for_Sale_ID\" "
                    + "FROM public.\"Cars_for_Sale \"";
            try{
                ResultSet rs = BD.query(sql);
                while(rs.next()){
                    int id = rs.getInt(1);
                    String label =rs.getString(1);
                    carforsaleCombobox.addItem(label);
                    ht_carforsaleID.put(label, id);
                }
            }catch(SQLException ex){   
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        car_Feature_IDCombobox = new javax.swing.JComboBox<>();
        carforsaleCombobox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Car for Sale ID:");

        jLabel3.setText("Car Feature ID:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Insert New Feature on car for sale");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        car_Feature_IDCombobox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                car_Feature_IDComboboxFocusLost(evt);
            }
        });
        car_Feature_IDCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                car_Feature_IDComboboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(carforsaleCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(car_Feature_IDCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(carforsaleCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(car_Feature_IDCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(cancelButton))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void car_Feature_IDComboboxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_car_Feature_IDComboboxFocusLost
        
    }//GEN-LAST:event_car_Feature_IDComboboxFocusLost

    private void car_Feature_IDComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_car_Feature_IDComboboxActionPerformed

    }//GEN-LAST:event_car_Feature_IDComboboxActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        Integer carforsale_ID = (Integer) ht_carforsaleID.get(carforsaleCombobox.getSelectedItem());
        Integer carfeature_ID = (Integer) ht_carFeatures.get(car_Feature_IDCombobox.getSelectedItem());
        
        StringBuilder sql = new StringBuilder("INSERT INTO public.\"features_on_Cars_for_Sale\"(\n" +
"	\"car_for_sale_ID\", \"car_Feature_ID\")\n" +
"	VALUES (");
        sql.append(carforsale_ID.intValue());
        sql.append(",");
        sql.append(carfeature_ID.intValue());
        sql.append(")");
        System.out.println(sql.toString());
        try {
            BD.update( sql.toString() );
            JOptionPane.showMessageDialog(this, "New Feature for a car on sale has been added!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error adding Feature for a car on sale: \n" + ex.toString());
            System.out.println( ex.getMessage() );
        }
        setVisible(false);
    }//GEN-LAST:event_addButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> car_Feature_IDCombobox;
    private javax.swing.JComboBox<String> carforsaleCombobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
